"""Public API for UC-02 pseudonymization (consumed by UC-03 + downstream)."""

from ucs.uc02_pseudonymization.code.envelope import (
    DEFAULT_MAX_RETRIES,
    DEFAULT_TIMEOUT_PER_ATTEMPT_S,
    ENVELOPE_SYS_HINT,
    MID_PATTERN,
    DETECTION_CLAUSES,
    TAG_PATTERN,
    EnvelopeIntegrityError,
    EnvelopeMapping,
    EnvelopeProviderError,
    IntegrityResult,
    MappingRegistry,
    check_envelope_integrity,
    compose_system_prompt,
    compose_user_prompt,
    make_detector,
    with_envelope,
)
from ucs.uc02_pseudonymization.code.pseudonymizer import (
    depseudonymize,
    detect_rule_based,
    pseudonymize,
    pseudonymize_text,
    merge_spans,
    restore_text,
    score_detection,
)

__all__ = [
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_TIMEOUT_PER_ATTEMPT_S",
    "DETECTION_CLAUSES",
    "ENVELOPE_SYS_HINT",
    "EnvelopeIntegrityError",
    "EnvelopeMapping",
    "EnvelopeProviderError",
    "IntegrityResult",
    "MID_PATTERN",
    "MappingRegistry",
    "TAG_PATTERN",
    "check_envelope_integrity",
    "compose_system_prompt",
    "compose_user_prompt",
    "make_detector",
    "depseudonymize",
    "detect_rule_based",
    "pseudonymize",
    "pseudonymize_text",
    "merge_spans",
    "restore_text",
    "score_detection",
    "with_envelope",
]
