"""Render ``utils/generation/models.py`` from ``catalog.json``.

The generated module is what the adapters import. It carries only the menu data
they need (ordered model ids, aliases, tiers per model, vendor default, migration
notices) plus the catalog's timestamp and per-source status, so a reader of the
adapters sees at once which CLI state the code was generated against. Rendering
is deterministic: the same catalog always produces the same text, which lets a
test assert that the committed module is current.
"""

from __future__ import annotations

import json
from pathlib import Path

# Providers are emitted in this order first; any other provider follows alphabetically.
_PROVIDER_ORDER = ("codex", "claude", "agy")

_HEADER = '''"""Model menus of the local CLIs. GENERATED, do not edit.

Generated by ``python -m utils.generation.catalog update`` from
``utils/generation/catalog/catalog.json`` (generated {generated_at}).
Edit ``catalog/overlay.toml`` or rerun the command; then commit both files.

Per provider ``<P>``:
    <P>_MODELS               ids in the CLI's own menu order
    <P>_ALIASES              alias -> id or alias (chains are followed by the adapters)
    <P>_TIERS                id -> reasoning tiers the CLI accepts for that model
    <P>_TIER_OPTIONS         union of the tiers above
    <P>_DEFAULT_TIER         the CLI's default tier ("" when the CLI has none)
    <P>_VENDOR_DEFAULT       the CLI's own menu default (NOT the thesis default,
                             which lives in utils/generation/__init__.py)
    <P>_MIGRATIONS           id -> replacement id announced by the CLI
    <P>_DEPRECATED           ids upstream marks deprecated
    <P>_MODEL_STRING_FORMAT  how the CLI spells model+tier ("{{model}}-{{tier}}" for agy)
"""
'''


def _literal(value, indent: int = 0) -> str:
    """Render tuples/dicts one element per line so the module stays ruff-clean."""
    pad = " " * indent
    inner = " " * (indent + 4)
    if isinstance(value, tuple):
        if not value:
            return "()"
        if len(value) == 1:  # ruff format keeps a one-element tuple on one line
            return f"({_literal(value[0], indent + 4)},)"
        items = "".join(f"{inner}{_literal(v, indent + 4)},\n" for v in value)
        return f"(\n{items}{pad})"
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = "".join(
            f"{inner}{json.dumps(k, ensure_ascii=False)}: {_literal(v, indent + 4)},\n"
            for k, v in value.items()
        )
        return f"{{\n{items}{pad}}}"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if value is None:
        return "None"
    return repr(value)


def _provider_block(name: str, provider: dict) -> str:
    """Render one provider's ``<PREFIX>_*`` constant block for the generated models module."""
    prefix = name.upper()
    rows = provider["models"]
    models = tuple(r["id"] for r in rows)
    aliases = dict(provider.get("aliases", {}))
    tiers = {r["id"]: tuple(r["tiers"]) for r in rows}
    migrations = {r["id"]: r["migration"] for r in rows if r.get("migration")}
    deprecated = tuple(r["id"] for r in rows if r.get("deprecated"))
    default = provider["default_model"]
    seen: set[str] = set()
    while default in aliases and default not in seen:
        seen.add(default)
        default = aliases[default]
    lines = [
        f"# ---- {name} ----",
        f"{prefix}_MODELS: tuple[str, ...] = {_literal(models)}",
        f"{prefix}_ALIASES: dict[str, str] = {_literal(aliases)}",
        f"{prefix}_TIERS: dict[str, tuple[str, ...]] = {_literal(tiers)}",
        f"{prefix}_TIER_OPTIONS: tuple[str, ...] = {_literal(tuple(provider['tier_options']))}",
        f"{prefix}_DEFAULT_TIER: str = {_literal(provider['default_tier'])}",
        f"{prefix}_VENDOR_DEFAULT: str = {_literal(default)}",
        f"{prefix}_MIGRATIONS: dict[str, str] = {_literal(migrations)}",
        f"{prefix}_DEPRECATED: tuple[str, ...] = {_literal(deprecated)}",
        f"{prefix}_MODEL_STRING_FORMAT: str | None = "
        f"{_literal(provider.get('model_string_format'))}",
    ]
    return "\n".join(lines) + "\n"


def render_models_module(catalog: dict) -> str:
    """Return the full text of ``models.py`` for ``catalog``."""
    providers = catalog["providers"]
    order = [p for p in _PROVIDER_ORDER if p in providers] + sorted(
        p for p in providers if p not in _PROVIDER_ORDER
    )
    sources = {
        name: f"{info.get('status', '?')} {info.get('message', '')}".strip()
        for name, info in sorted(catalog.get("sources", {}).items())
        if isinstance(info, dict) and "status" in info
    }
    parts = [
        _HEADER.format(generated_at=catalog["generated_at"]),
        "from __future__ import annotations\n",
        f"GENERATED_AT: str = {_literal(catalog['generated_at'])}",
        f"SCHEMA_VERSION: str = {_literal(catalog['schema_version'])}",
        f"CATALOG_PROVIDERS: tuple[str, ...] = {_literal(tuple(order))}",
        f"SOURCES: dict[str, str] = {_literal(sources)}",
        "",
    ]
    parts += [_provider_block(name, providers[name]) for name in order]
    return "\n".join(parts).rstrip("\n") + "\n"


def models_module_is_current(catalog: dict, path: Path) -> bool:
    """True when ``path`` holds exactly what ``catalog`` renders to."""
    return path.exists() and path.read_text(encoding="utf-8") == render_models_module(catalog)


def write_models_module(catalog: dict, path: Path) -> bool:
    """Write the rendered module atomically; return True when the file changed."""
    text = render_models_module(catalog)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise
    return True
