"""SQLModel entities for the shared substrate CRM database.

The substrate has two surfaces and the split decides what is a table here.

**CRM content (this file, persisted in ``substrate.db``)** -- everything a CRM
record actually consists of and that a user or an LLM tool could ask about at
run time: :class:`Contact`, :class:`Note`, :class:`Company`, :class:`Product`,
:class:`Order`, :class:`Review` and :class:`MessageBrief`. UC-03 reads contacts
and notes through its MCP tools and appends notes; the frontend bridge reads
contacts, briefs and the purchase history. The customer's own words -- the
review behind each order, in the English original and the Czech translation --
are CRM content too (decision D-DB-3, 2026-09-04): they are what UC-01 mirrors,
UC-04 mines and UC-03 searches, so they live in :class:`Review` with a full-text
index rather than in JSON files every use case re-parses.

**Derived customer attributes (also here).** What a CRM computes or receives
about a customer and then shows on the record: the lifecycle stage
(:class:`LifecycleStage` vocabulary + ``Contact.lifecycle_stage``, arithmetic
over the orders at build time) and what the recommender produced for the
person -- :class:`Recommendation`, :class:`Topic`, :class:`Aspect`. The latter
three are loaded by the database build from UC-04's committed result files,
exactly as the inferred OCEAN profiles are (decision 2026-09-04: UC-04 runs
first, its results are snapshots, the database carries them, UC-01 reads only
the database). They are empty until UC-04 has produced them, never fabricated.

**Experiment bookkeeping (deliberately not here)** -- generated messages, error
rows, evaluation records and judge fixtures live in committed JSON and CSV next
to the run that produced them, so every number in the thesis reproduces without
this git-ignored database. UC-02's PII answer key (planted messages + gold
spans) is likewise a snapshot artifact, regenerated from contact rows.
"""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import ClassVar, Optional

from sqlalchemy import Column, Index, Text
from sqlalchemy.types import JSON
from sqlmodel import Field, SQLModel

# Re-exported so `Note.category`'s vocabulary is discoverable at the model; it is
# defined in the leaf `substrate.constants` so UC-03's MCP path can import it
# without pulling SQLModel. See that module for the reasoning.
from substrate.constants import NOTE_CATEGORIES  # noqa: F401


# ---------------------------------------------------------------------------
# Domain enums
# ---------------------------------------------------------------------------


class ErrorType(str, Enum):
    """Structured error codes for non-success UC-01 outcomes.

    The single definition of the taxonomy. UC-01's batch pipeline currently
    emits these as bare string literals in ``_error_row``; wiring it to this
    enum is part of the UC-01 walkthrough.
    """

    MISSING_GENDER = "MISSING_GENDER"
    MISSING_FORMALITY = "MISSING_FORMALITY"
    MISSING_VOCATIVE = "MISSING_VOCATIVE"
    INVALID_NAME_FIELD = "INVALID_NAME_FIELD"
    GENERATION_FAILED = "GENERATION_FAILED"


# ---------------------------------------------------------------------------
# CRM content -- persisted entities
# ---------------------------------------------------------------------------


class Company(SQLModel, table=True):
    """
    Partner company a contact is affiliated with (the B2B half of the substrate).

    Eight rows, generated by ``substrate/generators/companies.py``. Registry
    fields mirror the shape of the Czech ARES public registry: the IČO carries a
    valid mod-11 check digit and the DIČ is its ``CZ``-prefixed form. Those two
    are also Czech personal-data identifiers, which makes them fixtures for
    UC-02 pseudonymisation.

    Resolved from :attr:`Contact.company_id`; UC-03's contact detail joins it so
    a reader sees the employer's name rather than a foreign key.

    The address is drawn the same way a contact's is — one ČSÚ municipality draw
    for city / postal code / district / region, same street format — so the
    substrate has one address shape rather than two.
    """

    __tablename__ = "uc_companies"

    id: Optional[int] = Field(default=None, primary_key=True)
    updated_at: Optional[datetime] = Field(
        default=None,
        description=(
            "When a UC-03 write last changed this row; NULL = untouched since the build. "
            "The review queue compares it before applying a held change."
        ),
    )
    name: str = Field(..., description="Company name, e.g. 'Acme s.r.o.' (synthetic)")
    # Czech public registry fields (ARES / RPO)
    ico: Optional[str] = Field(default=None, description="Czech/Slovak company ID (IČO), 8 digits")
    dic: Optional[str] = Field(default=None, description="VAT number (DIČ), e.g. 'CZ25596641'")
    # Address fields (mirrors Contact address layout for JOIN convenience)
    full_street: Optional[str] = Field(
        default=None, description="Street + house number, e.g. 'Dlouhá 5'"
    )
    city: Optional[str] = Field(default=None, description="Municipality name, e.g. 'Praha'")
    postal_code: Optional[str] = Field(default=None, description="Czech postal code, e.g. '11000'")
    district: Optional[str] = Field(
        default=None, description="LAU1 district of the municipality, e.g. 'Brno-město' (ČSÚ)"
    )
    region: Optional[str] = Field(
        default=None, description="NUTS3 region of the municipality, e.g. 'Jihomoravský kraj' (ČSÚ)"
    )
    legal_form: Optional[str] = Field(
        default=None, description="Legal form abbreviation, e.g. 's.r.o.' or 'a.s.'"
    )


class Product(SQLModel, table=True):
    """
    One item of the retailer's catalogue.

    18 213 rows built from ``snapshots/amazon/amazon-catalog-en.json``: the real
    Amazon Electronics catalogue behind the substrate's behavioural layer.
    Title, category and description stay in English (the source data is), the
    ``sku`` is the ASIN, and ``price`` is the USD list price converted at one
    fixed nominal rate. No metric in the thesis uses the absolute price; the
    constant only gives the Czech CRM a plausible currency scale, and 1 075
    catalogue entries carry no price at all.

    Joined with :class:`Order` to answer what a contact has bought.
    """

    __tablename__ = "uc_products"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(..., description="Product title as published in the Amazon catalogue")
    category: Optional[str] = Field(default=None, description="Catalogue category")
    price: Optional[float] = Field(
        default=None, description="List price in CZK, converted from USD; None when unpriced"
    )
    description: Optional[str] = Field(default=None, description="Catalogue description")
    sku: Optional[str] = Field(default=None, description="Stock-keeping unit — the Amazon ASIN")
    name_cs: Optional[str] = Field(
        default=None,
        description=(
            "Czech product title from the frozen translation run (16 067 of 18 213 products); "
            "NULL when the translator never saw the title. A prompt that wants Czech falls back "
            "to ``name`` itself; the database never invents one."
        ),
    )


class Contact(SQLModel, table=True):
    """
    Synthetic CRM person to be addressed. The centre of the substrate.

    How one row is built (``substrate/generators/contacts/``): an (age, sex) pair
    is drawn jointly from the ČSÚ age x sex table, Faker ``cs_CZ`` draws a name
    in the matching gendered form, ``vokativ`` builds the greeting, 70 % of
    contacts get ``formal=True``, 70 % get an OCEAN profile sampled from BFI-2
    norms and modulated by the two persisted CRMArena latents, and a PII overlay
    adds each identifier at the presence rate fixed in
    ``generators/contacts/_constants._PII_RATES``. Every contact therefore has a
    real age behind it, but only 20 % expose a birth date as a stored identifier.
    The runner then pairs the first 425 contacts with the stratified Amazon
    reviewers inside each group, matching genders wherever the reviewer's gender
    is known (``reviewer_gender`` / ``gender_paired``), and the assembler fills
    ``frequent_words``, ``prior_interactions`` and ``style_excerpt`` from that
    reviewer's translated Czech reviews (the reviews themselves are rows of
    :class:`Review`; these three columns are the prompt-ready digests).

    Clean-data preconditions for UC-01 generation:
    - gender must be 'm' or 'f' (never inferred; None -> MISSING_GENDER error)
    - formal must be True or False (None -> MISSING_FORMALITY error)
    - name_vocative required in main run (None -> MISSING_VOCATIVE error)

    Those three are violated on purpose by the 50 rows with ``is_clean=False``
    (all 50 lack the greeting, 13 lack gender, 13 lack formality). A fill rate
    below 500 on those columns is the fixture design, not a defect.
    """

    __tablename__ = "uc_contacts"

    id: Optional[int] = Field(default=None, primary_key=True)
    updated_at: Optional[datetime] = Field(
        default=None,
        description=(
            "When a UC-03 write last changed this row; NULL = untouched since the build. "
            "The review queue compares it before applying a held change."
        ),
    )
    first_name: str
    last_name: str
    nickname: Optional[str] = Field(
        default=None, description="Substitutes first_name in informal addressing"
    )
    gender: Optional[str] = Field(default=None, description="'m' | 'f' | None — NEVER inferred")
    formal: Optional[bool] = Field(default=None, description="True=vykání, False=tykání | None")
    name_vocative: Optional[str] = Field(
        default=None,
        description=(
            "Pre-computed full greeting string. "
            "Format: 'Vážený pane Nováku' / 'Vážená paní Nováková' / "
            "'Ahoj Lukáši' / 'Dobrý den,'."
        ),
    )
    company_id: Optional[int] = Field(
        default=None,
        foreign_key="uc_companies.id",
        description="Optional FK to Company for B2B affiliation",
    )
    title: Optional[str] = Field(
        default=None,
        description="Optional role/title, e.g. 'ředitel marketingu'",
    )
    # Enrichment fields
    ocean: Optional[dict[str, float]] = Field(
        default=None,
        # none_as_null keeps a missing profile as SQL NULL. Without it SQLAlchemy
        # stores the JSON text 'null', and `WHERE ocean IS NOT NULL` then matches
        # every row.
        sa_column=Column(JSON(none_as_null=True), nullable=True),
        description=(
            "dict[str,float] with keys exactly {O,C,E,A,N}, values on the "
            "1-5 BFI raw scale (rounded to 2 decimal places). "
            "Stored as JSON by SQLAlchemy; Python interface is a native dict. "
            "Single-letter keys minimise prompt-language pollution. "
            "Validation (key-set + range) is enforced by set_ocean(); "
            "direct dict assignment bypasses validation."
        ),
    )
    purchase_seniority: Optional[float] = Field(
        default=None,
        description=(
            "CRMArena latent on [0.1, 1.0]: how long-standing the buying relationship is. "
            "Persisted so the causal structure behind the OCEAN profile is observable — it "
            "shifts the O and C means by up to +-0.15. NULL for the defective contacts, which "
            "carry no personality profile."
        ),
    )
    relationship_warmth: Optional[float] = Field(
        default=None,
        description=(
            "CRMArena latent on [0.1, 1.0]: how warm the account relationship is. Shifts the "
            "E and A means by up to +-0.15. NULL for the defective contacts."
        ),
    )
    ocean_source: Optional[str] = Field(
        default=None,
        description=(
            "Provenance of the OCEAN profile, carried for the thesis rather than for any "
            "code path — no use case reads it. 'synthetic' (sampled from BFI-2 norms by the "
            "generator), 'inferred' (LLM-inferred from the contact's real reviews, "
            "ucs/uc01_personalization/snapshots/ocean_inferred.json), or NULL when the contact "
            "has no profile."
        ),
    )
    frequent_words: Optional[str] = Field(
        default=None,
        description=(
            "JSON list of the contact's up to 20 most frequent Czech tokens, counted over their "
            "translated reviews by the assembler; NULL for prospects and untranslated reviewers."
        ),
    )
    prior_interactions: Optional[str] = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
        description=(
            "Czech free text: the contact's six most recent translated review headlines, "
            "newest first, one per line with the star rating, written by the assembler. Text "
            "rather than JSON because UC-01 pastes it into a prompt as prose."
        ),
    )
    style_excerpt: Optional[str] = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
        description=(
            "A sample of the contact's own Czech prose for style mirroring: the longest "
            "translated review body that carries no gendered first-person form (the "
            "translator writes 'koupil jsem' for nearly everyone), or, when every body "
            "carries one, the longest body with those sentences cut out (D-DB-6, "
            "2026-09-04); cut to substrate.constants.STYLE_EXCERPT_CHARS, written by the "
            "assembler. NULL for prospects and for reviewers with no translated body."
        ),
    )
    reviewer_id: Optional[str] = Field(
        default=None,
        index=True,
        description=(
            "Amazon reviewerID join key into snapshots/amazon/amazon-original-en.json and "
            "amazon-translated-cz.json; NULL for the 75 prospects."
        ),
    )
    amazon_group: Optional[str] = Field(
        default=None,
        index=True,
        description="Amazon stratification group: 'A' | 'B' | 'C'; NULL for the 75 prospects.",
    )
    reviewer_gender: Optional[str] = Field(
        default=None,
        description=(
            "Gender of the real reviewer behind the history, inferred from their Amazon name "
            "and self-reference cues in the English reviews (snapshots/amazon/reviewer-gender.json): "
            "'m' | 'f' | NULL when unknown or a prospect."
        ),
    )
    gender_paired: bool = Field(
        default=False,
        index=True,
        description=(
            "True when reviewer_gender is known and equals this contact's gender, i.e. the "
            "purchase history and writing sample were left by someone of the same gender. "
            "The pairing step maximises this inside each group; select on it when a use case "
            "needs a gender-consistent behavioural layer."
        ),
    )
    # PII / contact-detail fields. Presence rates in generators/contacts/_constants._PII_RATES
    # mirror the sparse identifier coverage of a real CRM extract.
    email: Optional[str] = Field(
        default=None, description="Primary e-mail address, e.g. 'jan.novak@example.cz' (synthetic)"
    )
    phone: Optional[str] = Field(
        default=None,
        description="Phone number in Czech national format, e.g. '+420 601 000 000' (synthetic)",
    )
    full_street: Optional[str] = Field(
        default=None, description="Street + house number, e.g. 'Krátká 1' (synthetic)"
    )
    city: Optional[str] = Field(
        default=None, description="Municipality name, e.g. 'Brno' (synthetic)"
    )
    postal_code: Optional[str] = Field(
        default=None, description="Czech postal code, five digits without a space, e.g. '60200'"
    )
    district: Optional[str] = Field(
        default=None, description="LAU1 district of the municipality, e.g. 'Brno-město' (ČSÚ)"
    )
    region: Optional[str] = Field(
        default=None, description="NUTS3 region of the municipality, e.g. 'Jihomoravský kraj' (ČSÚ)"
    )
    date_of_birth: Optional[date] = Field(
        default=None, description="Date of birth (synthetic); a Czech personal-data identifier"
    )
    bank_account: Optional[str] = Field(
        default=None,
        description="Czech domestic bank account number, e.g. '1/0100' (synthetic)",
    )
    iban: Optional[str] = Field(
        default=None,
        description=(
            "Czech IBAN, e.g. 'CZ65 0100 0000 0000 0000 0001' (synthetic). When the contact "
            "also stores bank_account, the IBAN encodes that same account (D-DB-2)."
        ),
    )
    is_clean: bool = Field(
        default=True,
        description=(
            "False marks the 50 deliberately defective rows that exercise UC-01's "
            "MISSING_GENDER / MISSING_FORMALITY / MISSING_VOCATIVE guards."
        ),
    )
    lifecycle_stage: Optional[str] = Field(
        default=None,
        foreign_key="uc_lifecycle_stages.code",
        index=True,
        description=(
            "Where the customer stands (RFM stage code, see LifecycleStage): computed by the "
            "assembler from the order dates against the substrate reference date with "
            "substrate.lifecycle.classify_lifecycle; 'prospect' for the 75 contacts without an order."
        ),
    )

    # Class-level constants for OCEAN validation — ClassVar excludes from SQLModel column mapping
    OCEAN_KEYS: ClassVar[frozenset[str]] = frozenset({"O", "C", "E", "A", "N"})
    OCEAN_LOW: ClassVar[float] = 1.0  # BFI raw-scale minimum
    OCEAN_HIGH: ClassVar[float] = 5.0  # BFI raw-scale maximum

    def set_ocean(self, value: Optional[dict[str, float]]) -> None:
        """
        Validate and store an OCEAN dict on self.ocean.

        SQLAlchemy Column(JSON) handles serialisation; this method enforces
        the domain invariants (key-set + range) before assignment. The assembler
        (``substrate/pipeline/build_substrate_db.py``) routes every profile through
        it at build time, so a sampled or LLM-inferred value outside the scale
        fails the rebuild instead of entering the database.

        Raises:
            ValueError: if key set != {O,C,E,A,N} or any value is outside
                        [OCEAN_LOW, OCEAN_HIGH] (1.0–5.0 BFI raw scale).
        """
        if value is None:
            self.ocean = None
            return
        if set(value.keys()) != self.OCEAN_KEYS:
            raise ValueError(
                f"OCEAN dict must have keys exactly {self.OCEAN_KEYS}, got {set(value.keys())}"
            )
        for trait, v in value.items():
            if not isinstance(v, (int, float)):
                raise ValueError(f"OCEAN[{trait}] must be a float, got {type(v).__name__}")
            if not (self.OCEAN_LOW <= v <= self.OCEAN_HIGH):
                raise ValueError(
                    f"OCEAN[{trait}]={v} is outside [{self.OCEAN_LOW}, {self.OCEAN_HIGH}]"
                )
        self.ocean = value


class Order(SQLModel, table=True):
    """
    One purchase linking a :class:`Contact` to a :class:`Product`.

    45 951 rows, one per review in the contact's Amazon history, carrying the
    real review timestamps (1999-12-01 to 2014-07-23 — the upper bound is
    ``substrate.constants.SUBSTRATE_REFERENCE_DATE``, the substrate's one
    "today"). ``quantity`` is always 1 and ``unit_price`` is the catalogue price
    at build time, 0.0 for the unpriced products: neither is derived from the
    source data, so neither should carry a claim.

    This is the CRM's purchase history — what a contact bought and when. What
    the contact *said* about the purchase is the matching :class:`Review` row.
    """

    __tablename__ = "uc_orders"

    id: Optional[int] = Field(default=None, primary_key=True)
    contact_id: int = Field(
        ..., foreign_key="uc_contacts.id", description="FK to the Contact who placed the order"
    )
    product_id: int = Field(
        ..., foreign_key="uc_products.id", description="FK to the Product that was ordered"
    )
    quantity: int = Field(
        default=1, description="Always 1 — the source records one review per item"
    )
    unit_price: float = Field(default=0.0, description="Catalogue price in CZK at build time")
    order_date: Optional[date] = Field(
        default=None,
        description="Review date from the Amazon record; None when the source has none",
    )


class Review(SQLModel, table=True):
    """
    The customer's own words about one purchase, in both languages.

    45 951 rows, exactly one per :class:`Order` (the source records one review
    per item, so ``order_id`` is unique). The English columns are the Amazon
    original; the Czech columns are the frozen machine translation joined by
    item, present for 42 990 rows — the remaining 2 961 are translation loss
    (``snapshots/amazon/translation-coverage.json``) and stay NULL rather than
    fall back to English. ``rating`` and the two ``helpful_*`` counts come from
    the same record.

    This is the CRM's interaction history in prose: what UC-01 mirrors for
    style, what UC-04 mines for topics and aspects, what UC-03 can search. The
    assembler builds an FTS5 full-text index over the four text columns
    (``substrate.constants.REVIEWS_FTS_TABLE``); it is a virtual table, not an
    entity here. Decision D-DB-3 (2026-09-04): until then the text lived only in
    the two Amazon JSON snapshots and every use case re-parsed 100 MB of it.
    """

    __tablename__ = "uc_reviews"
    __table_args__ = (Index("ix_uc_reviews_contact_date", "contact_id", "review_date"),)

    id: Optional[int] = Field(default=None, primary_key=True)
    contact_id: int = Field(
        ..., foreign_key="uc_contacts.id", index=True, description="FK to the reviewing Contact"
    )
    order_id: int = Field(
        ...,
        foreign_key="uc_orders.id",
        unique=True,
        description="FK to the Order this review is about (one review per order)",
    )
    product_id: int = Field(
        ...,
        foreign_key="uc_products.id",
        index=True,
        description="FK to the reviewed Product (denormalised from the order for direct joins)",
    )
    rating: Optional[float] = Field(default=None, description="Star rating 1.0-5.0 from the source")
    helpful_up: int = Field(default=0, description="Helpful votes the review received")
    helpful_total: int = Field(default=0, description="Total votes cast on the review")
    review_date: Optional[date] = Field(
        default=None, description="Review date from the Amazon record; equals the order date"
    )
    summary_en: Optional[str] = Field(
        default=None, sa_column=Column(Text, nullable=True), description="English headline"
    )
    text_en: Optional[str] = Field(
        default=None, sa_column=Column(Text, nullable=True), description="English body"
    )
    summary_cs: Optional[str] = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
        description="Czech headline from the frozen translation; NULL when untranslated",
    )
    text_cs: Optional[str] = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
        description="Czech body from the frozen translation; NULL when untranslated",
    )


class Note(SQLModel, table=True):
    """
    CRM note attached to a Contact.

    The substrate seeds 80 Czech notes (``author = "seed"``); UC-03's MCP server
    appends, edits and deletes notes at run time. ``category`` is one of
    :data:`NOTE_CATEGORIES`. ``author`` says who wrote the row: ``seed`` for the
    generator, ``human`` for a person typing in the demo, ``llm:<model>`` when a
    language model filed it through the server. ``audit_seq`` is the sequence
    number of the hash-chained audit row of the tool call that wrote it, so a
    reviewer can walk from the note to the call and back.
    """

    __tablename__ = "uc_notes"

    id: Optional[int] = Field(default=None, primary_key=True)
    contact_id: int = Field(..., foreign_key="uc_contacts.id", index=True)
    content: str = Field(..., description="Note body text.")
    category: Optional[str] = Field(
        default=None,
        description="Optional note category assigned by a caller/categorizer.",
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
    pseudonymized: bool = Field(
        default=False,
        description="True when the note body passed through the UC-02 envelope on its way in.",
    )
    author: str = Field(
        default="seed",
        description="Who wrote the row: 'seed', 'human', or 'llm:<model>'.",
    )
    audit_seq: Optional[int] = Field(
        default=None,
        description="Sequence number of the UC-03 audit row of the call that wrote this note.",
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description=(
            "When a UC-03 write last changed this note; NULL = never edited. Every edit or "
            "deletion must name the value it read (optimistic concurrency by timestamp)."
        ),
    )


class ChangeLog(SQLModel, table=True):
    """
    One field change requested through UC-03's MCP server.

    Written for every ``update_contact`` / ``update_company`` call. Under the
    ``strict`` security profile the change is recorded but **not applied**
    (``applied = False``) until a person reviews it (``review.py``); under
    ``open`` and ``masked`` it is applied at once and the row is the record of
    what the model changed. Every change names the ``updated_at`` the model read
    (``entity_updated_at``); the server refuses a stale one and a held change is
    applied only while the entity still carries that timestamp. The timestamp
    moves on every write, so it is the only guard needed. ``old_value`` / ``new_value`` are stored as text so
    a reviewer can read them without knowing the column type.
    """

    __tablename__ = "uc_change_log"

    id: Optional[int] = Field(default=None, primary_key=True)
    entity_type: str = Field(..., description="'contact' or 'company'.")
    entity_id: int = Field(..., index=True)
    field: str = Field(..., description="Column name that was (or is to be) changed.")
    old_value: Optional[str] = Field(default=None)
    new_value: Optional[str] = Field(default=None)
    author: str = Field(..., description="'human' or 'llm:<model>'.")
    audit_seq: Optional[int] = Field(default=None)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    entity_updated_at: Optional[datetime] = Field(
        default=None,
        description=(
            "The entity's updated_at the model read and passed back; a held change is applied "
            "only while the entity still carries it (optimistic concurrency by timestamp)."
        ),
    )
    applied: bool = Field(default=False, description="True once the value is on the row.")
    reviewed_at: Optional[datetime] = Field(default=None)
    review_outcome: Optional[str] = Field(
        default=None,
        description="'applied', 'rejected', or 'conflict' (the field moved before the review).",
    )


class LifecycleStage(SQLModel, table=True):
    """
    The customer lifecycle vocabulary: one row per stage code.

    Seven rows seeded at build from ``substrate.constants.LIFECYCLE_STAGES``:
    six RFM stages (Berry & Linoff ch. 5, Kumar & Reinartz section 6.1) plus
    ``prospect`` for a contact that never bought. Keyed by the code so a query
    stays readable (``WHERE lifecycle_stage = 'churned'``); the Czech and English
    labels live here, once, and a prompt or a screen joins them. ``rule`` states
    the threshold in words for a reader of the database.
    """

    __tablename__ = "uc_lifecycle_stages"

    code: str = Field(primary_key=True, description="Stage code, e.g. 'loyal_active'")
    label_cs: str = Field(
        ..., description="Czech label a prompt pastes, e.g. 'dlouhodobě věrný zákazník'"
    )
    label_en: str = Field(..., description="English label")
    rule: str = Field(..., description="The threshold that assigns the stage, in words")


class Recommendation(SQLModel, table=True):
    """
    A product the recommender (UC-04) picked for a contact, with its Czech reason.

    Loaded at build from UC-04's committed handoff file (``ucs/uc04_matchmaker/
    results/uc04_to_uc01_handoff.json``): the top-K of the collaborative-filtering
    arm with a one-sentence rationale written by a model, for the contacts UC-04
    covered (108 today). UC-01's hyper-personalisation level pastes these; a CRM
    would show them as "next best offer". Empty until UC-04 has run.
    """

    __tablename__ = "uc_recommendations"

    id: Optional[int] = Field(default=None, primary_key=True)
    contact_id: int = Field(..., foreign_key="uc_contacts.id", index=True)
    rank: int = Field(..., description="Position in the contact's list, 1 = best")
    product_id: Optional[int] = Field(
        default=None,
        foreign_key="uc_products.id",
        description="FK to the recommended Product; NULL when the ASIN is not in the catalogue",
    )
    asin: str = Field(..., description="Amazon ASIN of the recommended item")
    score: Optional[float] = Field(
        default=None,
        description="Recommender score; NULL when the item fell outside the scored window",
    )
    reason_cs: Optional[str] = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
        description="One-sentence Czech rationale",
    )
    evidence_asins: Optional[str] = Field(
        default=None, description="JSON list of the contact's own ASINs the rationale points to"
    )
    source: Optional[str] = Field(
        default=None, description="Which UC-04 arm / prompt produced the row"
    )


class Topic(SQLModel, table=True):
    """
    An interest theme the recommender (UC-04) found in a contact's purchases.

    Loaded at build from the same handoff file: up to five clusters per contact
    over the titles of what they bought (LDA by default), each a label of top
    terms, a weight and a few evidence titles. Empty until UC-04 has run.
    """

    __tablename__ = "uc_topics"

    id: Optional[int] = Field(default=None, primary_key=True)
    contact_id: int = Field(..., foreign_key="uc_contacts.id", index=True)
    rank: int = Field(..., description="Position in the contact's list, 1 = heaviest")
    label: str = Field(..., description="Topic label, the top terms joined by ' / '")
    weight: Optional[float] = Field(default=None, description="Cluster weight for this contact")
    evidence_titles: Optional[str] = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
        description="JSON list of product titles behind the topic",
    )
    paradigm: Optional[str] = Field(
        default=None, description="Clustering method: lda | kmeans | bertopic | llm"
    )


class Aspect(SQLModel, table=True):
    """
    What a contact praises or criticises about products (aspect-based sentiment, UC-04).

    Loaded at build from the handoff file's ``absa`` block. Empty today: the
    per-contact aspect aggregate was never produced; the table exists so UC-01's
    aspect level has a place to read from the day UC-04 fills it.
    """

    __tablename__ = "uc_aspects"

    id: Optional[int] = Field(default=None, primary_key=True)
    contact_id: int = Field(..., foreign_key="uc_contacts.id", index=True)
    aspect: str = Field(..., description="The product feature, e.g. 'price_value'")
    sentiment: str = Field(..., description="positive | negative | neutral")
    evidence: Optional[str] = Field(
        default=None,
        sa_column=Column(Text, nullable=True),
        description="Quoted review passage behind the verdict",
    )


class MessageBrief(SQLModel, table=True):
    """
    CRM message in its non-personalised default form.

    25 operator-authored templates the CRM holds and an operator picks from.
    Assembled from ``substrate/snapshots/briefs/message_briefs.json``; UC-01's
    batch pipeline reads that snapshot directly, the demo reads this table.

    category: organisational label aligned with CRMArena task taxonomy
              (huang2025crmarena §3).
    default_template: ready-to-send Czech text without any personalisation
                      (the 1st tier). Higher tiers take this text as the
                      template and rewrite it with customer data.
    """

    __tablename__ = "uc_message_briefs"

    id: Optional[int] = Field(default=None, primary_key=True)
    title: str = Field(..., description="Stable identifier, e.g. 'seasonal_sale_launch'")
    default_template: str = Field(
        ...,
        description="Ready-to-send Czech text for tier 1 (no personalisation)",
    )
    category: Optional[str] = Field(
        default=None,
        description=(
            "Organisational label (invitation | upsell | followup | onboarding | "
            "engagement | educational | newsletter | other)"
        ),
    )
