"""Model menus of the local CLIs. GENERATED, do not edit.

Generated by ``python -m utils.generation.catalog update`` from
``utils/generation/catalog/catalog.json`` (generated 2026-09-07T11:28:51Z).
Edit ``catalog/overlay.toml`` or rerun the command; then commit both files.

Per provider ``<P>``:
    <P>_MODELS               ids in the CLI's own menu order
    <P>_ALIASES              alias -> id or alias (chains are followed by the adapters)
    <P>_TIERS                id -> reasoning tiers the CLI accepts for that model
    <P>_TIER_OPTIONS         union of the tiers above
    <P>_DEFAULT_TIER         the CLI's default tier ("" when the CLI has none)
    <P>_VENDOR_DEFAULT       the CLI's own menu default (NOT the thesis default,
                             which lives in utils/generation/__init__.py)
    <P>_MIGRATIONS           id -> replacement id announced by the CLI
    <P>_DEPRECATED           ids upstream marks deprecated
    <P>_MODEL_STRING_FORMAT  how the CLI spells model+tier ("{model}-{tier}" for agy)
"""

from __future__ import annotations

GENERATED_AT: str = "2026-09-07T11:28:51Z"
SCHEMA_VERSION: str = "1.0"
CATALOG_PROVIDERS: tuple[str, ...] = (
    "codex",
    "claude",
    "agy",
)
SOURCES: dict[str, str] = {
    "agy": "OK 14 models from `agy models` (live)",
    "claude": "OK alias map extracted from installed binary (5 aliases)",
    "claude-docs": "OK vendor default claude-opus-5[1m] for account type 'max' (fetched)",
    "codex": "OK 6 models from ~/.codex/models_cache.json",
    "models.dev": "OK fetched",
}

# ---- codex ----
CODEX_MODELS: tuple[str, ...] = (
    "gpt-6-astra",
    "gpt-5.6-sol",
    "gpt-5.6-terra",
    "gpt-5.6-luna",
    "gpt-5.5",
    "gpt-5.4-mini",
)
CODEX_ALIASES: dict[str, str] = {}
CODEX_TIERS: dict[str, tuple[str, ...]] = {
    "gpt-6-astra": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
        "ultra",
    ),
    "gpt-5.6-sol": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
        "ultra",
    ),
    "gpt-5.6-terra": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
        "ultra",
    ),
    "gpt-5.6-luna": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
    "gpt-5.5": (
        "low",
        "medium",
        "high",
        "xhigh",
    ),
    "gpt-5.4-mini": (
        "low",
        "medium",
        "high",
        "xhigh",
    ),
}
CODEX_TIER_OPTIONS: tuple[str, ...] = (
    "low",
    "medium",
    "high",
    "xhigh",
    "max",
    "ultra",
)
CODEX_DEFAULT_TIER: str = "medium"
CODEX_VENDOR_DEFAULT: str = "gpt-6-astra"
CODEX_MIGRATIONS: dict[str, str] = {
    "gpt-5.4-mini": "gpt-5.6-luna",
}
CODEX_DEPRECATED: tuple[str, ...] = ()
CODEX_MODEL_STRING_FORMAT: str | None = "{model} {tier}"

# ---- claude ----
CLAUDE_MODELS: tuple[str, ...] = (
    "claude-opus-5",
    "claude-opus-5[1m]",
    "claude-sonnet-5",
    "claude-sonnet-5[1m]",
    "claude-haiku-4-5",
    "claude-fable-5",
    "claude-fable-5-1",
)
CLAUDE_ALIASES: dict[str, str] = {
    "best": "fable",
    "default": "claude-opus-5[1m]",
    "fable": "claude-fable-5-1",
    "haiku": "claude-haiku-4-5",
    "opus": "claude-opus-5",
    "opusplan": "opus",
    "sonnet": "claude-sonnet-5",
}
CLAUDE_TIERS: dict[str, tuple[str, ...]] = {
    "claude-opus-5": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
    "claude-opus-5[1m]": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
    "claude-sonnet-5": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
    "claude-sonnet-5[1m]": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
    "claude-haiku-4-5": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
    "claude-fable-5": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
    "claude-fable-5-1": (
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
    ),
}
CLAUDE_TIER_OPTIONS: tuple[str, ...] = (
    "low",
    "medium",
    "high",
    "xhigh",
    "max",
)
CLAUDE_DEFAULT_TIER: str = "medium"
CLAUDE_VENDOR_DEFAULT: str = "claude-opus-5[1m]"
CLAUDE_MIGRATIONS: dict[str, str] = {}
CLAUDE_DEPRECATED: tuple[str, ...] = ()
CLAUDE_MODEL_STRING_FORMAT: str | None = None

# ---- agy ----
AGY_MODELS: tuple[str, ...] = (
    "gemini-3.8-flash",
    "gemini-3.7-flash",
    "gemini-3.6-flash",
    "gemini-3.1-pro",
    "claude-sonnet-4-6",
    "claude-opus-4-6-thinking",
    "gpt-oss-120b",
)
AGY_ALIASES: dict[str, str] = {}
AGY_TIERS: dict[str, tuple[str, ...]] = {
    "gemini-3.8-flash": (
        "low",
        "medium",
        "high",
    ),
    "gemini-3.7-flash": (
        "low",
        "medium",
        "high",
    ),
    "gemini-3.6-flash": (
        "low",
        "medium",
        "high",
    ),
    "gemini-3.1-pro": (
        "low",
        "high",
    ),
    "claude-sonnet-4-6": (),
    "claude-opus-4-6-thinking": (),
    "gpt-oss-120b": ("medium",),
}
AGY_TIER_OPTIONS: tuple[str, ...] = (
    "low",
    "medium",
    "high",
)
AGY_DEFAULT_TIER: str = "medium"
AGY_VENDOR_DEFAULT: str = "gemini-3.8-flash"
AGY_MIGRATIONS: dict[str, str] = {}
AGY_DEPRECATED: tuple[str, ...] = ()
AGY_MODEL_STRING_FORMAT: str | None = "{model}-{tier}"
